title = "BLOCKCHAIN CONFIG"

[Network]
    Type="channel"
    CAFile="assets/sdk_ca/ca.crt"
    Cert="assets/sdk_ca/sdk.crt"
    Key="assets/sdk_ca/sdk.key"
    NodeURL=""

    RpcNodeURL=""
    GroupID=1

[Account]
    KeyFile="assets/contract/*.pem"

[Chain]
    ChainID=1
    SMCrypto=false

[Contract]
    Address=""

